Trace prepared statement name
exaring/otelpgx pull request #24
Opened 2023-09-25 13:21 UTC by lzakharov

Add prepared statement name to the trace attributes.

2023-09-25 14:11 UTC, obitech approved these changes
LGTM

2023-09-29 06:51 UTC, costela requested changes
thanks for the contribution! :rocket:

2023-09-29 06:51 UTC, costela commented on tracer.go
> +	PrepareStmtNameKey = attribute.Key("pgx.prepare_stmt.name")
not a blocker for this MR, but this feels like something that could be added to semconv: https://github.com/open-telemetry/semantic-conventions/blob/9790d8f54533840dd187d3ffa5c2546d9420d357/docs/database/sql.md

2023-09-29 06:51 UTC, costela commented on tracer.go
>  	}
minor: AFAIK we still can have non-prepared statements, so maybe we could only add this if the statement has a name?

```suggestion
	}
	
	if data.Name != "" {
		trace.WithAttributes(PrepareStmtNameKey.String(data.Name)),
	}
```

2023-09-29 15:56 UTC, costela approved these changes
thanks again! :pray:

2023-09-29 15:56 UTC, merged